import Header from '@/components/Header';
import Head from 'next/head';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Canva</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          {/*Header*/}

          <Header/>
          {/*Body*/}
          <div className="body">
           <p className="">What will you design today?</p>
           </div>
           <div className="para">
           <p>Canva makes it easy to create professional designs and to share or print them.</p>
           
           
           </div>
  
          {/*Footer*/}
        </div>
  
  );
}
